### ISSUE TITLE
What changes are implemented for 0.2.0?

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP2Community/CommunityFixes#37] opened 2023-12-20 20:34 UTC
0.8.0 was released last week, but KSP 2 0.2.0 was released yesterday.  There is no information as to what is being done here.  As such, it seems to be almost as bad as malware

**Comment by jan-bures** [comment] 2023-12-20 20:52
No bug fixes specific to 0.2.0 have been added yet, it has after all, as you say, been only out for a single day, and we have a lot of other mods that are actually broken to fix, while I haven't encountered any errors with this mod (therefore marking it as compatible with the update).

 The full list of currently implemented fixes is in the [README.md](https://github.com/KSP2Community/CommunityFixes/blob/main/README.md) file visible on the main page of the repository, so I don't understand what you mean about there being no information, or that whole malware remark (especially for something that's open source and you can read through the not-very-large codebase to see that what we say it does is what it really does).

If you have any specific suggestions for what should be improved, then please let us know.

**Comment by linuxgurugamer** [comment] 2023-12-20 20:54
The question is, how do you know if the fixes you have in here were not fixed already?  I think you need to test to be sure that all the fixes are still necessary, and don't cause problems

I've been modding for a while, releasing something like this without testing after a major update isn't really the thing to do.  

Also, on the forum, no posts were made since March 30, has nothing changed since then?

Thanks for replying

**Comment by jan-bures** [comment] 2023-12-20 21:28
Yes, I am definitely planning on doing some testing of what fixes are and are not needed in 0.2.0, I just have had a lot on my plate these past few days, including COVID, so I haven't gotten around to updating the mod yet, I simply checked whether the current version breaks anything, which it didn't seem to.

I will definitely post an update in the forum thread when I get around to releasing the new version, I honestly just forgot for the 0.5 release, so that's on me.

**Comment by jan-bures** [comment] 2023-12-21 18:17
Mod has been updated for the 0.2.0 update, with current fixes verified as still working as intended (and still needed) and a new fix added. The forum page has been updated with the changelog of all the missing versions and the latest version. Hopefully that resolves this issue.

**Closed by jan-bures** 2023-12-21 18:17 UTC
Labels: bug

**Comment by linuxgurugamer** [comment] 2023-12-21 21:18
Appreciate the update
